#!/bin/bash
## Add the public key if exists
mkdir ~/.ssh
if test -n "${sshPubKey-}"; then
  echo "Public key is found"
  echo ${sshPubKey}>> ~/.ssh/authorized_keys
  service ssh start
  echo "SSH server started"
else
  echo "Public key is not found"
  echo "SSH server will not be started"
fi
